version: "3"
services:
  model:
    build: ./docker_images/jupyter
    volumes:
      - ./.git:/app/.git:ro
      - ./data:/app/data:ro
      - ./scripts:/app/scripts:ro
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./tmp:/tmp/alphasea-example-model
    working_dir: /app
    environment:
      ALPHASEA_AGENT_BASE_URL: ${ALPHASEA_AGENT_BASE_URL:-http://host.docker.internal:8070}
      ALPHASEA_MODEL_ID: ${ALPHASEA_MODEL_ID}
      ALPHASEA_MODEL_PATH: ${ALPHASEA_MODEL_PATH:-/app/data/example_model.xz}
      ALPHASEA_LOG_LEVEL: debug
      ALPHASEA_SYMBOLS: ${ALPHASEA_SYMBOLS:-BTC,ETH,XRP,LINK,ATOM,DOT,SOL,BNB,MATIC,ADA}
      ALPHASEA_POSITION_NOISE: ${ALPHASEA_POSITION_NOISE:-0}
    command: python -m src.main
    user: root
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
    extra_hosts:
      - "host.docker.internal:host-gateway"
